version: '3'

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    ports:
      - "27017:27017"

  replay-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "mongodb"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/
      REPLAY_SERVICE_ADDRESS: 0.0.0.0:8080
      REPLAY_SERVICE_TOKEN: SUPER_SECRET_TOKEN
