version: '3'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - ./data:/var/lib/postgresql/data

  replay-service:
    build: .
    ports:
      - "80:8080"
    depends_on:
      - "db"
    environment:
      REPLAY_DB_URL: postgres://postgres:secret@db:5432/
      REPLAY_SERVICE_ADDRESS: 0.0.0.0:8080
      REPLAY_SERVICE_TOKEN: MEH
