on: [push, pull_request]

name: ci frontend

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd frontend
      - run: npm ci
      - run: npm run lint
  
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd frontend
      - run: npm ci
      - run: npm run build
